import { fontVariables } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import "@stackloom/ui/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={cn(fontVariables, "font-sans")}
      >
        {children}
      </body>
    </html>
  );
}
