pub mod provider;
pub mod repo;
pub mod service;

pub use provider::OAuthProvider;
pub use repo::OAuthRepository;
pub use service::OAuthService;

use neocrates::response::error::{AppError, AppResult};

/// A registered OAuth2 client application (tenant-scoped).
#[derive(Debug, Clone)]
pub struct OAuthClient {
    pub id: i64,
    pub tenant_id: i64,
    pub name: String,
    pub client_id: String,
    /// The Argon2-hashed client secret. Never returned to callers.
    pub client_secret_hash: String,
    pub redirect_uris: Vec<String>,
    pub allowed_scopes: Vec<String>,
    pub status: i16,
    pub description: Option<String>,
}

/// An issued OAuth2 token pair.
#[derive(Debug, Clone)]
pub struct OAuthToken {
    pub id: i64,
    pub oauth_client_id: i64,
    pub user_id: i64,
    pub tenant_id: i64,
    pub access_token: String,
    pub refresh_token: String,
    pub scopes: Vec<String>,
    pub access_token_expires_at: i64,  // Unix timestamp seconds
    pub refresh_token_expires_at: i64, // Unix timestamp seconds
    pub revoked_at: Option<i64>,
}

/// Third-party OAuth provider binding.
#[derive(Debug, Clone)]
pub struct OAuthProviderBinding {
    pub id: i64,
    pub user_id: i64,
    pub provider: String,
    pub provider_user_id: String,
    pub provider_username: Option<String>,
    pub provider_email: Option<String>,
}

/// User information returned by a third-party provider.
#[derive(Debug, Clone)]
pub struct OAuthProviderUserInfo {
    pub provider: String,
    pub provider_user_id: String,
    pub provider_username: Option<String>,
    pub provider_email: Option<String>,
    pub display_name: Option<String>,
}

/// Command to create a new OAuth2 client application.
///
/// The HTTP layer populates `tenant_id`, `name`, `client_secret`, `redirect_uris`,
/// `allowed_scopes`, and `description`. The infra service generates `client_id` (UUID)
/// and computes `client_secret_hash` (Argon2) before calling the repository.
#[derive(Debug, Clone)]
pub struct CreateOAuthClientCmd {
    pub tenant_id: i64,
    pub name: String,
    /// Plaintext secret — set by HTTP layer; will be hashed by service before persistence.
    pub client_secret: String,
    /// Public identifier — generated by service (UUID, no dashes).
    pub client_id: String,
    /// Argon2 hash of client_secret — set by service before calling repo.
    pub client_secret_hash: String,
    pub redirect_uris: Vec<String>,
    pub allowed_scopes: Vec<String>,
    pub description: Option<String>,
}

impl CreateOAuthClientCmd {
    /// Validate user-provided fields before entering the service.
    pub fn validate(&self) -> AppResult<()> {
        if self.name.trim().is_empty() {
            return Err(AppError::ValidationError("name cannot be empty".to_string()));
        }
        if self.client_secret.trim().is_empty() {
            return Err(AppError::ValidationError(
                "client_secret cannot be empty".to_string(),
            ));
        }
        if self.redirect_uris.is_empty() {
            return Err(AppError::ValidationError(
                "at least one redirect_uri is required".to_string(),
            ));
        }
        if self.allowed_scopes.is_empty() {
            return Err(AppError::ValidationError(
                "at least one scope is required".to_string(),
            ));
        }
        Ok(())
    }
}

/// Command to update an existing OAuth2 client.
#[derive(Debug, Clone)]
pub struct UpdateOAuthClientCmd {
    pub id: i64,
    pub name: Option<String>,
    pub redirect_uris: Option<Vec<String>>,
    pub allowed_scopes: Option<Vec<String>>,
    pub status: Option<i16>,
    pub description: Option<String>,
}

/// Command to rotate the client secret.
#[derive(Debug, Clone)]
pub struct RotateOAuthClientSecretCmd {
    pub id: i64,
    /// New plaintext secret — will be hashed by infra before persistence.
    pub new_client_secret: String,
}

/// Command to initiate an OAuth2 authorization_code flow.
#[derive(Debug, Clone)]
pub struct AuthorizeCmd {
    pub client_id: String,
    pub redirect_uri: String,
    pub scopes: Vec<String>,
    pub state: String,
    pub code_challenge: String,
    /// Only "S256" is accepted.
    pub code_challenge_method: String,
    /// Authenticated user issuing the authorization.
    pub user_id: i64,
    pub tenant_id: i64,
}

impl AuthorizeCmd {
    /// Validate the authorization command before entering the service.
    pub fn validate(&self) -> AppResult<()> {
        if self.client_id.trim().is_empty() {
            return Err(AppError::ValidationError(
                "client_id cannot be empty".to_string(),
            ));
        }
        if self.redirect_uri.trim().is_empty() {
            return Err(AppError::ValidationError(
                "redirect_uri cannot be empty".to_string(),
            ));
        }
        if self.scopes.is_empty() {
            return Err(AppError::ValidationError(
                "at least one scope is required".to_string(),
            ));
        }
        if self.code_challenge_method.as_str() != "S256" {
            return Err(AppError::ValidationError(
                "only S256 code_challenge_method is supported".to_string(),
            ));
        }
        if self.code_challenge.trim().is_empty() {
            return Err(AppError::ValidationError(
                "code_challenge cannot be empty".to_string(),
            ));
        }
        Ok(())
    }
}

/// Command to exchange an authorization code for a token pair.
#[derive(Debug, Clone)]
pub struct ExchangeCodeCmd {
    pub code: String,
    pub code_verifier: String,
    pub redirect_uri: String,
    pub client_id: String,
    pub client_secret: String,
}

impl ExchangeCodeCmd {
    /// Validate the exchange command before entering the service.
    pub fn validate(&self) -> AppResult<()> {
        if self.code.trim().is_empty() {
            return Err(AppError::ValidationError("code cannot be empty".to_string()));
        }
        if self.code_verifier.trim().is_empty() {
            return Err(AppError::ValidationError(
                "code_verifier cannot be empty".to_string(),
            ));
        }
        Ok(())
    }
}

/// Command to refresh an OAuth2 access token using a refresh token.
#[derive(Debug, Clone)]
pub struct RefreshOAuthTokenCmd {
    pub refresh_token: String,
    pub client_id: String,
    pub client_secret: String,
}

impl RefreshOAuthTokenCmd {
    /// Validate the refresh command before entering the service.
    pub fn validate(&self) -> AppResult<()> {
        if self.refresh_token.trim().is_empty() {
            return Err(AppError::ValidationError(
                "refresh_token cannot be empty".to_string(),
            ));
        }
        Ok(())
    }
}

/// Command to revoke an OAuth2 token (access or refresh).
#[derive(Debug, Clone)]
pub struct RevokeOAuthTokenCmd {
    pub token: String,
    pub client_id: String,
    pub client_secret: String,
}

/// Command to bind a third-party provider identity to a user.
#[derive(Debug, Clone)]
pub struct BindOAuthProviderCmd {
    pub user_id: i64,
    pub provider_info: OAuthProviderUserInfo,
}

/// Result returned after a successful authorization code issuance.
#[derive(Debug, Clone)]
pub struct AuthorizeResult {
    /// Short-lived one-time authorization code.
    pub code: String,
    /// Echo back the state for CSRF validation on the client side.
    pub state: String,
}
