#!/usr/bin/env python3
"""
gen_seed_migration.py
---------------------
Reads system-level seed data from the running database and writes
INSERT ... ON CONFLICT DO NOTHING statements to the target migration file.

Usage:
    python3 scripts/gen_seed_migration.py

Database connection is read from backend/config.yml (base-database.url).
Output file: backend/migrations/basemigrate/20260507180000_seed_initial_data.sql
"""

import re
import os
import psycopg2
import psycopg2.extras

# ── config ──────────────────────────────────────────────────────────────────

SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT    = os.path.dirname(SCRIPT_DIR)
CONFIG_FILE  = os.path.join(REPO_ROOT, "backend", "config.yml")
OUTPUT_FILE  = os.path.join(
    REPO_ROOT,
    "backend", "migrations", "basemigrate",
    "20260507180000_seed_initial_data.sql",
)

def read_db_url(config_path: str) -> str:
    with open(config_path) as f:
        content = f.read()
    m = re.search(r"base-database:\s*\n\s*url:\s*(\S+)", content)
    if not m:
        raise RuntimeError("Cannot find base-database.url in config.yml")
    return m.group(1)

# ── helpers ──────────────────────────────────────────────────────────────────

def lit(v) -> str:
    """Convert a Python value to a SQL literal."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    # string – escape single quotes
    s = str(v).replace("'", "''")
    return f"'{s}'"

def row_to_insert(table: str, row: dict) -> str:
    cols = ", ".join(row.keys())
    vals = ", ".join(lit(v) for v in row.values())
    return f"INSERT INTO {table} ({cols}) VALUES ({vals})\nON CONFLICT DO NOTHING;"

# ── queries (system-only filters) ────────────────────────────────────────────

QUERIES = {
    "dicts": """
        SELECT * FROM dicts
        WHERE tenant_id IS NULL AND deleted_at IS NULL
        ORDER BY sort, id
    """,
    "menus": """
        SELECT * FROM menus
        WHERE tenant_id IS NULL AND deleted_at IS NULL
          AND code ~ '^[A-Z]'
        ORDER BY sort, id
    """,
    "perms": """
        SELECT * FROM perms
        WHERE tenant_id IS NULL AND deleted_at IS NULL
        ORDER BY sort, id
    """,
    "roles": """
        SELECT * FROM roles
        WHERE tenant_id IS NULL AND deleted_at IS NULL
          AND id IN (
              SELECT MIN(id) FROM roles
              WHERE tenant_id IS NULL AND deleted_at IS NULL
              GROUP BY code
          )
        ORDER BY sort, id
    """,
    "tenants": """
        SELECT * FROM tenants
        WHERE id = 617700000000000001
    """,
    "users": """
        SELECT * FROM users
        WHERE id = 617700000000000002
    """,
    "user_tenants": """
        SELECT * FROM user_tenants
        WHERE user_id = 617700000000000002
    """,
    "user_tenant_roles": """
        SELECT utr.* FROM user_tenant_roles utr
        JOIN user_tenants ut ON ut.id = utr.user_tenant_id
        WHERE ut.user_id = 617700000000000002
    """,
    "role_menus": """
        SELECT rm.* FROM role_menus rm
        WHERE rm.role_id IN (
            SELECT MIN(id) FROM roles
            WHERE tenant_id IS NULL AND deleted_at IS NULL
            GROUP BY code
        )
        ORDER BY rm.role_id, rm.menu_id
    """,
    "role_perms": """
        SELECT rp.* FROM role_perms rp
        WHERE rp.role_id IN (
            SELECT MIN(id) FROM roles
            WHERE tenant_id IS NULL AND deleted_at IS NULL
            GROUP BY code
        )
        ORDER BY rp.role_id, rp.perm_id
    """,
}

TABLE_ORDER = [
    "tenants", "users", "roles", "menus", "perms",
    "user_tenants", "user_tenant_roles", "role_menus", "role_perms",
    "dicts",
]

# ── main ─────────────────────────────────────────────────────────────────────

def main():
    db_url = read_db_url(CONFIG_FILE)
    print(f"Connecting to: {db_url}")

    conn = psycopg2.connect(db_url)
    conn.autocommit = True
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)

    sections = []
    total = 0
    for table in TABLE_ORDER:
        if table not in QUERIES:
            continue
        cur.execute(QUERIES[table])
        rows = cur.fetchall()
        if not rows:
            continue
        stmts = [row_to_insert(table, dict(r)) for r in rows]
        sections.append((table, stmts))
        print(f"  {table}: {len(rows)} rows")
        total += len(rows)

    cur.close()
    conn.close()

    lines = [
        "-- ============================================================",
        "-- INITIAL DATA SEED  (generated by scripts/gen_seed_migration.py)",
        "-- ============================================================",
        "-- Runs before: 20260508000000_seed_perms.sql",
        "--",
        "-- Seeds the minimum data required for a fresh deployment.",
        "-- All statements use ON CONFLICT DO NOTHING (fully idempotent).",
        "-- After running migrations restart the app to warm the Redis",
        "-- perm-action cache (startup warm-up in app/src/lib.rs).",
        "--",
        "-- Default admin credentials: admin / Admin@123456",
        "-- ============================================================",
        "",
    ]
    for table, stmts in sections:
        sep = "-- " + "=" * 58
        lines += [sep, f"-- {table.upper()}", sep]
        lines += stmts
        lines.append("")

    output = "\n".join(lines)
    with open(OUTPUT_FILE, "w") as f:
        f.write(output)

    print(f"\nWrote {total} rows → {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
