import type { MenuItem } from "@/lib/tree"

export const BASE_CURRENT_MENU_ITEMS: MenuItem[] = [
  {
    id: "base-root",
    pid: "0",
    name: "后台管理",
    code: "base-root",
    icon: "LayoutGrid",
    path: "/",
    sort: 0,
    visible: 1,
    remark: "Stackloom 管理后台入口",
  },
  {
    id: "upms-group",
    pid: "base-root",
    name: "账号与权限",
    code: "upms",
    icon: "ShieldCheck",
    path: "/upms",
    sort: 1,
    visible: 1,
    remark: "用户、角色、租户与权限模块",
  },
  {
    id: "tools-group",
    pid: "base-root",
    name: "系统工具",
    code: "tools",
    icon: "BookMarked",
    path: "/tools",
    sort: 2,
    visible: 1,
    remark: "配置业务基础能力和通用字典",
  },
  {
    id: "upms-users",
    pid: "upms-group",
    name: "用户管理",
    code: "upms-users",
    icon: "Users",
    path: "/upms/users",
    sort: 1,
    visible: 1,
    remark: "维护系统用户资料、账号状态与联系方式",
  },
  {
    id: "upms-tenants",
    pid: "upms-group",
    name: "租户管理",
    code: "upms-tenants",
    icon: "Building2",
    path: "/upms/tenants",
    sort: 2,
    visible: 1,
    remark: "维护学校、校区与部门等层级租户结构",
  },
  {
    id: "upms-menus",
    pid: "upms-group",
    name: "菜单管理",
    code: "upms-menus",
    icon: "Waypoints",
    path: "/upms/menus",
    sort: 3,
    visible: 1,
    remark: "维护导航菜单、路由配置与层级结构",
  },
  {
    id: "tools-dicts",
    pid: "tools-group",
    name: "字典管理",
    code: "tools-dicts",
    icon: "BookMarked",
    path: "/tools/dicts",
    sort: 1,
    visible: 1,
    remark: "维护树形字典项、键值和扩展配置",
  },
]
